version: '3.8'

services:
  app:
    image: tms/bm-np
    build:
      context: .
    restart: always
    container_name: bm-np
    ports:
      - '8080:8080'
    depends_on:
      - db

  db:
    image: postgres:16
    restart: on-failure
    container_name: postgres-db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root